---

sudo: required
# https://docs.travis-ci.com/user/osx-ci-environment
language: objective-c
matrix:
  include:
    # macOS 10.12
    - osx_image: xcode8.2
    # macOS 10.11
    - osx_image: xcode8

before_install:
  # Uninstall preinstalled Homebrew
  - 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" </dev/null'
  - rm -rf /usr/local/Homebrew
  - sudo rm -rf /usr/local/Caskroom
  - rm -rf /usr/local/bin/brew

install:
  # Debug info
  - python --version
  # Install pip
  - sudo easy_install pip
  # Install Ansible
  - sudo pip install ansible --quiet
  # Debug info
  - pip --version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  # Install required dependencies.
  - ansible-galaxy install danbohea.homebrew

script:
  # Syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run test playbook
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Idempotence test (run test playbook again & check output)
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
